dist: trusty
sudo: required

# Install Yarn package manager
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

# Build doc website - ends up in website/build/docusaurus-site directory
after_success:
  - cd website
  - yarn install
  - yarn run build

# Publish new Doc Website to Github Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./website/build/docusaurus-site
  on:
    branch: master